import argparse
import numpy as np
from dotenv import load_dotenv
load_dotenv()


def get_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="ICL time series classification evaluation.")

    # Experiment
    parser.add_argument("--exp_id", type=str, default="1")
    parser.add_argument("--random_seed", type=int, default=2021)

    # Logging
    parser.add_argument("--project", type=str, default="aviramom-/ts-icl")
    parser.add_argument("--use_wandb", type=int, default=0)
    parser.add_argument("--override_run", type=int, default=1)
    parser.add_argument("--keys_to_match", type=list,
                        default=["exp_id", "random_seed", "task_id", "method", "prompt_format"])

    # Model
    parser.add_argument("--method", type=str, default="random_baseline")
    parser.add_argument("--model_path", type=str, default="")
    parser.add_argument("--cache_dir", type=str, default="")
    parser.add_argument("--quantization", type=str, choices=["none", "4bit", "8bit"],
                        default="none")
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--low_cpu_mem_usage", action="store_true", default=True)

    # Data
    parser.add_argument("--data_path", type=str,
                        default="/cs/azencot_fsas/multimodal_ts/datasets/")
    parser.add_argument("--num_samples", type=int, default=None,
                        help="Max test samples per run (None = all)")

    # Task
    parser.add_argument("--task_id", type=str, default="icl_ucr_GunPoint",
                        help="Dataset task id, e.g. icl_ucr_GunPoint or icl_tse_3")

    # TimeSeriesExam-specific
    parser.add_argument("--tse_data_path", type=str, default="qa_dataset_augmented.json",
                        help="Path to augmented TSE dataset (generated by scripts/generate_tse_augmented.py)")
    parser.add_argument("--tse_test_fraction", type=float, default=0.3,
                        help="Fraction of TSE variants reserved for the test (query) split")

    # ICL / few-shot
    parser.add_argument("--picking_strategy", type=str, default="random",
                        choices=["first", "random", "medoid", "medoid_dtw", "reversed"])
    parser.add_argument("--num_shots", type=int, default=1)
    parser.add_argument("--use_label_desc", type=int, default=0,
                        help="1 = inject domain description.txt into prompt")
    parser.add_argument("--desc_dir", type=str, default="ucr_descriptions")
    parser.add_argument("--prompt_format", type=str, default=None,
                        choices=["no_support", "desc_first", "no_desc", "desc_last", "tse_official"],
                        help="Prompt structure. no_support=zero-shot with question only; "
                             "desc_first=question then examples then query; "
                             "no_desc=examples only; "
                             "desc_last=examples then question then query; "
                             "tse_official=official TSE MCQ format (zero-shot when --num_shots 0, ICL otherwise)")

    # Inference
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--display_samples", type=int, default=3)

    return parser


def get_retrieval_parser() -> argparse.ArgumentParser:
    """Argument parser for run_retrieval.py (Experiment 1 — retrieval baseline study)."""
    parser = argparse.ArgumentParser(description="Retrieval baseline study on TimeSeriesExam.")

    # Experiment
    parser.add_argument("--exp_id", type=str, default="retrieval_baseline")
    parser.add_argument("--random_seed", type=int, default=42)

    # Logging
    parser.add_argument("--project", type=str, default="aviramom-/ts-icl")
    parser.add_argument("--use_wandb", type=int, default=0)
    parser.add_argument("--override_run", type=int, default=1)
    parser.add_argument("--keys_to_match", type=list,
                        default=["exp_id", "random_seed", "method", "retrieval_strategies"])

    # Model
    parser.add_argument("--method", type=str, default="random_baseline")
    parser.add_argument("--cache_dir", type=str, default="")
    parser.add_argument("--quantization", type=str, choices=["none", "4bit", "8bit"],
                        default="none")
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--low_cpu_mem_usage", action="store_true", default=True)
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--display_samples", type=int, default=3)

    # Data
    parser.add_argument("--qa_dataset_path", type=str, default="qa_dataset.json",
                        help="Path to official TSE dataset (746 questions)")

    # Retrieval conditions
    parser.add_argument("--retrieval_strategies", type=str, nargs="+",
                        default=["all"],
                        help="Strategies to evaluate. 'all' runs all six conditions: "
                             "zero_shot random ts_only text_only fusion oracle")
    parser.add_argument("--retrieval_k", type=int, nargs="+", default=[0, 1, 2, 3, 5, 8],
                        help="Demonstration budgets to sweep over")
    parser.add_argument("--fusion_alpha", type=float, nargs="+", default=[0.25, 0.5, 0.75],
                        help="TS weights for the fusion strategy (swept independently)")
    parser.add_argument("--n_splits", type=int, default=5,
                        help="Number of cross-template splits (accuracy reported as mean±std)")
    parser.add_argument("--test_fraction", type=float, default=0.2,
                        help="Fraction of templates held out as query set per split")

    # Index
    parser.add_argument("--text_encoder", type=str, default="all-MiniLM-L6-v2",
                        help="sentence-transformers model for text index")
    parser.add_argument("--ts_max_len", type=int, default=128,
                        help="Points to include per TS in the prompt (subsampled from 1024)")

    return parser


def create_parser(notebook: bool = False):
    parser = get_parser()
    parsed = parser.parse_args("") if notebook else parser.parse_args()

    if hasattr(parsed, "quantization") and parsed.quantization == "none":
        parsed.quantization = None
    if hasattr(parsed, "cache_dir") and parsed.cache_dir == "":
        parsed.cache_dir = None

    return parsed
